name: 'Create A Release Branch Weekly'
description: 'Create A Release Branch GitHub Action'
author: 'Ehsan Sarshar'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  baseNumber:
    description: 'the number to start release with for example here baseNumber 3 `"release-2303"`'
    default: '0'
  numberOfWeeks:
    description: 'create release branch on each number of weeks'
    default: '1'
  baseDate:
    description: 'base date to check if specific number of weeks are passed'
    required: true
outputs:
  branchName:
    description: 'The ref for the (newly-created) branch'
  branchCreated:
    description: 'Boolean value representing whether or not a new branch was created.'
runs:
  using: 'node16'
  main: 'dist/index.js'
